//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom
    {
        public int RoomID { get; set; }
        public Nullable<int> ClassRoomID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<System.TimeSpan> StartClassTime { get; set; }
        public Nullable<System.TimeSpan> EndClassTime { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Course Course { get; set; }
    }
}
