//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.ClassRooms = new HashSet<ClassRoom>();
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int CourseID { get; set; }
        public int CourseNumber { get; set; }
        public Nullable<int> ProfessorID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> maxStudents { get; set; }
        public System.TimeSpan StartClassTime { get; set; }
        public System.TimeSpan EndClassTime { get; set; }
        public Nullable<bool> CourseFull { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRoom> ClassRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
